#ifndef ERRORCODE_H
#define ERRORCODE_H

enum ErrorCode {
    ERROR_NONE = 0,
    ERROR_DIVISION_BY_ZERO = 1001,
    ERROR_INVALID_INPUT = 1002,
    ERROR_FILE_NOT_FOUND = 1003,
    ERROR_OUT_OF_MEMORY = 1004,
    ERROR_NULL_REFERENCE = 1005,
};

#endif